// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_pq6EweNAWy84LG79XD5ef1GmjrVLvPM',
    appId: '1:1017282167387:web:1ccc325e735e6b096af57e',
    messagingSenderId: '1017282167387',
    projectId: 'my-routines-288c4',
    authDomain: 'my-routines-288c4.firebaseapp.com',
    storageBucket: 'my-routines-288c4.firebasestorage.app',
    measurementId: 'G-WMS9T5DFHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPsYFjyiTCrIDOG0klSdJsWid4nRWnouw',
    appId: '1:1017282167387:android:5b215280815c15306af57e',
    messagingSenderId: '1017282167387',
    projectId: 'my-routines-288c4',
    storageBucket: 'my-routines-288c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsTNP4zUCI7-h_HoZIfamNRNNHxwuXweg',
    appId: '1:1017282167387:ios:4ffc5f54907736fd6af57e',
    messagingSenderId: '1017282167387',
    projectId: 'my-routines-288c4',
    storageBucket: 'my-routines-288c4.firebasestorage.app',
    iosClientId: '1017282167387-k763en0qle99gbscfu3ub0fbit3gj50v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myRoutines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsTNP4zUCI7-h_HoZIfamNRNNHxwuXweg',
    appId: '1:1017282167387:ios:4ffc5f54907736fd6af57e',
    messagingSenderId: '1017282167387',
    projectId: 'my-routines-288c4',
    storageBucket: 'my-routines-288c4.firebasestorage.app',
    iosClientId: '1017282167387-k763en0qle99gbscfu3ub0fbit3gj50v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myRoutines',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_pq6EweNAWy84LG79XD5ef1GmjrVLvPM',
    appId: '1:1017282167387:web:6aa6503f451c49bb6af57e',
    messagingSenderId: '1017282167387',
    projectId: 'my-routines-288c4',
    authDomain: 'my-routines-288c4.firebaseapp.com',
    storageBucket: 'my-routines-288c4.firebasestorage.app',
    measurementId: 'G-HGLX541SVW',
  );
}
